### ISSUE TITLE
make a js bookmark version

### ISSUE THREAD

**Issue by idontknoiw** [Enchoseon/better-edpuzzle-userscript#1]
make a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionmake a js bookmark versionv

**Comment by Enchoseon** [comment]
Bookmarklets only run in the context of their window. Even if it could get around CORs to access the YouTube iframe, it'd still execute after the page loads so it wouldn't be able to intercept the API response—because of this I don't feel like reworking my script for bookmarklet form—if you're up to the task, go ahead.
